name: Build and Release EXE

on:
  push:
    tags:
      - 'v*' # Chạy mỗi khi bạn push một tag bắt đầu bằng 'v' (ví dụ: v1.0.0)

jobs:
  build:
    runs-on: windows-latest # Chạy trên máy ảo Windows của GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Phiên bản Python bạn đang dùng

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          python build.py

      - name: Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PWH_SK }}
          private-key: ${{ secrets.PWH_KEY }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/PyWarehouse.exe # Đính kèm file exe đã build xong
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }} # Tự động cấp quyền tạo Release
